R/stubs.R
Just in case we forget the `L` suffix.
=> Make sure line and column are integers

R/stubs.R, man/navigateToFile.Rd
This PR (alongside newer versions of the RStudio IDE) will allow users to request that the IDE preserve the previous cursor position when navigating to a file.
https://github.com/rstudio/rstudio/pull/1305
Note that the current behavior is preserved when running against older version of the IDE; that is, attempting to navigate to position `[-1, -1]` works the same as `[1, 1]` because RStudio transforms the positions to be valid behind the scenes.
=> preserve cursor position when invoking 'navigateToFile'

R/document-methods.R
Makes rstudioapi::getSourceEditorContext() return NULL if there is no open source editor pane.
The previous fix just changed the error message (now the failing line is as.document_selection(NULL) throwing Error: 'x' should be a list of {range, text} pairs)
=> Actually fix getSourceEditorContext()

R/stubs.R
On Windows paths containing non-ASCII characters will be returned in UTF-8 encoding but with implicit Encoding(...) of native.
Thus, the returned path is mis-encoded.
=> Fix getActiveProject() for non-ASCII file paths

R/themes.R, man/getThemeInfo.Rd
We removed `color` and `background` from the return value in PR 3608 of https://github.com/rstudio/rstudio. This PR updates the documentation to match.
=> Clean up Roxygen comments for getThemeInfo

R/themes.R, man/addTheme.Rd
This is a small change motivated by theme installation instructions beginning to appear in the wild, e.g.:
https://github.com/gadenbuie/yule-rstudio
https://github.com/batpigandme/night-owlish
Ideally the "install and apply my theme" code snippet featured in these repos would be a single line of R code. This change makes that possible by adding some logic to the `addTheme` API wrapper:
1. If the theme path given looks like a URL, it's downloaded first.
2. If the theme path given looks like a .tmtheme, it's converted first.
After the change, you can download, install, and apply a theme in a single step:
rstudioapi::addTheme("https://raw.githubusercontent.com/gadenbuie/yule-rstudio/master/Yule-RStudio.rstheme", apply = TRUE)
=> Download and/or convert theme as appropriate

R/themes.R
Currently, if you add a theme via URL, its filename on disk appears exactly as it did in the URL; in other words, you are liable to end up with filenames like "My%20Theme.rstheme". 
This change URL-decodes the theme filename before transforming into a path on disk.
=> URL decode theme filenames

vignettes/r-session.Rmd
Adds a bit to the R session vignette to show rstudioapi users how to call rstudioapi methods at startup.
=> Describe init at session start

R/code.R, R/remote.R, man/isAvailable.Rd, rstudioapi.Rproj
Re: https://github.com/rstudio/rstudio/issues/4490.
This PR implements a (somewhat primitive) mechanism for performing IPC with the parent RStudio session. A pair of files are used to transfer 'requests' / 'responses'; the requests made by `rstudioapi` are just serialized R calls that can be evaluated in the main R session, and the responses can later be read after they are written by the parent session.
This PR communicates through plain files for a couple reasons:
1. Since the relationship here is 1-1, and there's no notion of a "queue" of actions, just using a regular file keeps things simple.
2. R's own solutions for this don't appear appropriate: `socketConnection()` are network sockets, and so require a host + port and the host of issues that accompany those. `fifo()` seem like an …
=> allow rstudioapi to communicate with RStudio from child procs

R/stubs.R
This is necessary for paths that contain multi-bytes chars on Windows. Otherwise it displays as Garbage.
1. On Windows
1. Run `rstudioapi::selectFile()`
1. Select any file contains multiple-bytes.
You will find garbage letters in the output. After being marked as UTF-8, it becomes correct.
This API calls some functions I believe registered with RStudio, so the root cause may embeded in [RStudioAPI.cpp](https://github.com/rstudio/rstudio/blob/6a7328a4ce6caa10f521a821e2524c9f26445290/src/cpp/session/modules/RStudioAPI.cpp) and the fixes should be made there.
=> need to mark the returned path as UTF-8

NEWS.md, R/stubs.R, man/navigateToFile.Rd
This PR updates the code and documentation to add a default value for the `file` argument in `navigateToFile`. When `file` is not passed, the default value passed is an empty character. The IDE interprets an empty file to be the file currently in the user's view.
=> Set default value for navigateToFile

R/code.R, R/stubs.R, man/navigateToFile.Rd
This PR adds a boolean `moveCursor` to `navigateToFile`. The default value is TRUE which moves the cursor to the specified and line and column of the file if one is specified. If `moveCursor = false` is specified, then the call will scroll to the line and column so they are visible, but not move the users cursor.
=> Add moveCursor option to navigateToFile

R/remote.R
Unfortunately, a "NULL" call object can't be easily created, so we round-trip via a list to insert NULLs at appropriate positions.
=> fix #188 NULL arguments in callRemote

vignettes/visual-mode.Rmd
The editor is "What you see is what you mean" (rather than "get") since it's only editing semantics not final document appearance.
=> Change nomenclature to WYSIWYM

DESCRIPTION
Seems like a good idea, no matter what, and this has happy interactions with `usethis::browse_package()`.
=> Add pkgdown site to URL field of DESCRIPTION

R/stubs.R, man/sourceMarkers.Rd
This is the doc change for rstudio/rstudio#10278
I've replaced the note about the message allowing HTML since it doesn't work and could be exploited.
=> Update sourceMarkers doc

R/stubs.R, man/sendToConsole.Rd
related to https://github.com/rstudio/rstudio/pull/10366
Should the function have some logic to complain if the underlying `.rs.api.sendToConsole()` does not have the argument yet ?
=> add `sendToConsole(animate = TRUE)`

NEWS.md, R/document-api.R, R/document-methods.R, man/rstudio-editors.Rd
Companion to https://github.com/rstudio/rstudio/pull/10872.
Closes https://github.com/rstudio/rstudioapi/issues/251.
=> implement support for requesting document context by id

R/bug-report.R
Otherwise, the bug and new labels don't show up.
After the template is open, can always delete the contents
Addresses #235
=> Update BugReport template

DESCRIPTION, R/dialogs.R, R/remote.R, man/showDialog.Rd, man/showPrompt.Rd, man/showQuestion.Rd, rstudioapi.Rproj
An alternate approach to https://github.com/rstudio/rstudioapi/pull/301. @jonovik, can you let me know what you think?
=> use custom (extended) timeout for showDialog

R/bug-report.R
Per `?osVersion`, it is documented to sometimes be `NULL`. That would break `renderTemplate()`.
=> Robust to NULL osVersion
